nelmio_cors:
    defaults:
        allow_origin:
            - '*'
        allow_methods:
            - 'GET'
            - 'POST'
            - 'PUT'
            - 'DELETE'
            - 'OPTIONS'
        allow_headers:
            - 'Authorization'
            - 'Content-Type'
            - 'X-Requested-With'
        max_age: 3600
        expose_headers:
            - 'Link'
    paths:
        '^/api/': ~
